version: '3'

services:
  postgres-user-db:
    image: postgres:16
    environment:
      POSTGRES_USER: wt
      POSTGRES_PASSWORD: wt
      POSTGRES_DB: wt_user_service
    volumes:
      - ./init_scripts/01_ddl.sql:/docker-entrypoint-initdb.d/01_ddl.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q -U wt -d wt_user_service" ]
      interval: 5s
      timeout: 2s
      retries: 10

  user-service:
    build: .
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      postgres-user-db:
        condition: service_healthy
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "curl", "-fs", "http://localhost:8081/actuator/health" ]
      interval: 5s
      timeout: 2s
      retries: 10
