version: '3'

volumes:
  postgres_data:
    driver: local

services:
  postgres_db:
    image: postgres:16
    environment:
      POSTGRES_USER: wt
      POSTGRES_PASSWORD: wt
      POSTGRES_DB: wt_user_service
    ports:
      - "5432:5432"
    volumes:
#      - ./db_data_volume:/var/lib/postgresql/data
      - ./init_scripts/01_ddl.sql:/docker-entrypoint-initdb.d/01_ddl.sql