server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wt_user_service
    username: wt
    password: wt
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
